CREATE TABLE IF NOT EXISTS USERS (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN
);

CREATE TABLE IF NOT EXISTS FRIENDS (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    user_one_Id INT NOT NULL,
    user_two_Id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN,
    FOREIGN KEY (user_one_Id) REFERENCES USERS(Id),
    FOREIGN KEY (user_two_Id) REFERENCES USERS(Id),
    UNIQUE (user_one_Id, user_two_Id),
    CHECK (user_one_Id != user_two_Id)
);

CREATE TABLE IF NOT EXISTS CHANNELS (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN,
);

CREATE TABLE IF NOT EXISTS USERS_CHANNELS (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    channel_Id INT NOT NULL,
    user_Id INT NOT NULL,
    role TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN,
    FOREIGN KEY (channel_Id) REFERENCES CHANNELS(Id),
    FOREIGN KEY (user_Id) REFERENCES USERS(Id)
);

CREATE TABLE IF NOT EXISTS MESSAGES (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    sender_Id INT NOT NULL,
    friends_Id INT,
    channel_Id INT,
    message TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN,
    FOREIGN KEY (sender_Id) REFERENCES USERS(Id),
    FOREIGN KEY (friends_Id) REFERENCES FRIENDS(Id),
    FOREIGN KEY (channel_Id) REFERENCES CHANNELS(Id)
);